name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Main test and build job
  test-and-build:
    name: Test and Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [20, 21]
        package-manager: [yarn, npm]

    steps:
    - name: Setup Environment
      uses: ./.github/workflows/setup.yml
      with:
        node-version: ${{ matrix.node-version }}
        package-manager: ${{ matrix.package-manager }}
        install-system-deps: true
        verify-tools: true

    - name: Run linter
      run: yarn lint

    - name: Check code formatting
      run: yarn pretty:check

    - name: Check spelling
      run: yarn spell:check

    - name: Run security audit
      run: yarn audit:check

    - name: Run tests (excluding system-dependent tests)
      run: yarn test --testPathIgnorePatterns="scripts/other/__tests__" --testPathIgnorePatterns="src/archive/rar.test.ts" --testPathIgnorePatterns="src/archive/seven-zip.test.ts" --testPathIgnorePatterns="src/utils/storage.test.ts"

    - name: Run tests with coverage (excluding system-dependent tests)
      run: yarn test --coverage --testPathIgnorePatterns="scripts/other/__tests__" --testPathIgnorePatterns="src/archive/rar.test.ts" --testPathIgnorePatterns="src/archive/seven-zip.test.ts" --testPathIgnorePatterns="src/utils/storage.test.ts"

    - name: Build project
      run: yarn build

    - name: Package project
      run: yarn package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}-${{ matrix.package-manager }}
        path: |
          dist/
        retention-days: 30

  # Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-manager: [yarn, npm]

    steps:
    - name: Setup Environment
      uses: ./.github/workflows/setup.yml
      with:
        node-version: '20'
        package-manager: ${{ matrix.package-manager }}
        install-system-deps: false
        verify-tools: false

    - name: Run security audit
      run: yarn audit

  # Type checking
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-manager: [yarn, npm]

    steps:
    - name: Setup Environment
      uses: ./.github/workflows/setup.yml
      with:
        node-version: '20'
        package-manager: ${{ matrix.package-manager }}
        install-system-deps: false
        verify-tools: false

    - name: Type check
      run: yarn tsc --noEmit
