name: Native Builds

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'src/**'
      - 'deps/**'
      - 'package.json'
      - 'yarn.lock'
      - 'vite.pkg.config.ts'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'src/**'
      - 'deps/**'
      - 'package.json'
      - 'yarn.lock'
      - 'vite.pkg.config.ts'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-native:
    name: Build Native Executables
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup
      with:
        node-version: '20'
        package-manager: 'yarn'
        install-system-deps: 'true'
        verify-tools: 'true'

    - name: Run tests
      run: yarn test

    - name: Build native executables
      run: yarn package

    - name: List generated executables
      run: |
        echo "Generated executables:"
        ls -la dist/native/romorganizer*
        echo "File sizes:"
        du -h dist/native/romorganizer*

    - name: Test native executables
      run: |
        echo "Testing native executables..."
        if [ "${{ matrix.platform }}" = "linux" ]; then
          ./dist/native/romorganizer-linux-x64 --help
        elif [ "${{ matrix.platform }}" = "macos" ]; then
          ./dist/native/romorganizer-macos-arm64 --help
        fi

    - name: Upload native build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: native-builds-${{ matrix.platform }}
        path: |
          dist/native/romorganizer-*
        retention-days: 30

    - name: Create platform-specific archive
      run: |
        cd dist/native
        if [ "${{ matrix.platform }}" = "linux" ]; then
          tar -czf ../../romorganizer-linux.tar.gz romorganizer-linux-*
          zip -r ../../romorganizer-linux.zip romorganizer-linux-*
        elif [ "${{ matrix.platform }}" = "macos" ]; then
          tar -czf ../../romorganizer-macos.tar.gz romorganizer-macos-*
          zip -r ../../romorganizer-macos.zip romorganizer-macos-*
        fi

    - name: Upload platform archives
      uses: actions/upload-artifact@v4
      with:
        name: native-archives-${{ matrix.platform }}
        path: |
          romorganizer-${{ matrix.platform }}.tar.gz
          romorganizer-${{ matrix.platform }}.zip
